INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AU', 'Австралія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AT', 'Австрія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AZ', 'Азербайджан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AX', 'Аландські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AL', 'Албанія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DZ', 'Алжир');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AS', 'Американське Самоа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AO', 'Ангола');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AI', 'Анґілья');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AD', 'Андорра');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AQ', 'Антарктика');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AG', 'Антиґуа і Барбуда');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AR', 'Аргентина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AW', 'Аруба');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AF', 'Афганістан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BS', 'Багамські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BD', 'Бангладеш');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BB', 'Барбадос');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BH', 'Бахрейн');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BZ', 'Беліз');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BE', 'Бельґія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BJ', 'Бенін');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BM', 'Бермудські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BY', 'Білорусь');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BG', 'Болгарія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BO', 'Болівія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BA', 'Боснія і Герцеґовина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BW', 'Ботсвана');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BR', 'Бразілія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IO', 'Британська територія в Індійському Океані');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VG', 'Британські Віргінські острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BN', 'Бруней');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BF', 'Буркіна-Фасо');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BI', 'Бурунді');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BT', 'Бутан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VU', 'Вануату');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VA', 'Ватикан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GB', 'Велика Британія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VE', 'Венесуела');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('UM', 'Віддалені острови США');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VI', 'Віргінські острови, США');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AM', 'Вірменія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VN', 'Вʼєтнам');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GA', 'Габон');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('HT', 'Гаїті');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GM', 'Гамбія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GH', 'Гана');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GN', 'Гвінея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GW', 'Гвінея-Бісау');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('HN', 'Гондурас');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('HK', 'Гонконг, О.А.Р. Китаю');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GR', 'Греція');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GE', 'Грузія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GY', 'Ґайана');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GP', 'Ґваделупа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GT', 'Ґватемала');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GG', 'Ґернсі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GI', 'Ґібралтар');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GD', 'Ґренада');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GL', 'Ґренландія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GU', 'Ґуам');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DK', 'Данія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('JE', 'Джерсі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DJ', 'Джибуті');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DG', 'Дієго-Гарсія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DM', 'Домініка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DO', 'Домініканська Республіка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('EC', 'Еквадор');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GQ', 'Екваторіальна Гвінея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ER', 'Еритрея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SZ', 'Есватіні');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('EE', 'Естонія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ET', 'Ефіопія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('EG', 'Єгипет');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('YE', 'Ємен');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ZM', 'Замбія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('EH', 'Західна Сахара');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ZW', 'Зімбабве');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IL', 'Ізраїль');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IN', 'Індія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ID', 'Індонезія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IQ', 'Ірак');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IR', 'Іран');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IE', 'Ірландія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IS', 'Ісландія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ES', 'Іспанія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IT', 'Італія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('JO', 'Йорданія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CV', 'Кабо-Верде');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KZ', 'Казахстан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KY', 'Кайманові Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KH', 'Камбоджа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CM', 'Камерун');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CA', 'Канада');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IC', 'Канарські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('QA', 'Катар');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KE', 'Кенія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KG', 'Киргизстан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CN', 'Китай');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CY', 'Кіпр');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KI', 'Кірібаті');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CC', 'Кокосові (Кілінґ) Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CO', 'Колумбія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KM', 'Комори');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CG', 'Конго – Браззавіль');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CD', 'Конго – Кіншаса');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('XK', 'Косово');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CR', 'Коста-Ріка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CI', 'Кот-дʼІвуар');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CU', 'Куба');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KW', 'Кувейт');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CW', 'Кюрасао');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LA', 'Лаос');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LV', 'Латвія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LS', 'Лесото');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LT', 'Литва');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LR', 'Ліберія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LB', 'Ліван');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LY', 'Лівія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LI', 'Ліхтенштейн');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LU', 'Люксембурґ');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MR', 'Мавританія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MU', 'Маврікій');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('YT', 'Майотта');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MO', 'Макао, О.А.Р Китаю');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MW', 'Малаві');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MY', 'Малайзія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ML', 'Малі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MV', 'Мальдіви');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MT', 'Мальта');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MA', 'Марокко');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MQ', 'Мартініка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MH', 'Маршаллові Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MX', 'Мексика');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FM', 'Мікронезія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MZ', 'Мозамбік');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MD', 'Молдова');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MC', 'Монако');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MN', 'Монголія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MS', 'Монтсеррат');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MM', 'Мʼянма (Бірма)');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NA', 'Намібія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NR', 'Науру');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NP', 'Непал');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NE', 'Нігер');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NG', 'Нігерія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NL', 'Нідерланди');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BQ', 'Нідерландські Карибські острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NI', 'Нікараґуа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('DE', 'Німеччина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NU', 'Ніуе');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NZ', 'Нова Зеландія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NC', 'Нова Каледонія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NO', 'Норвеґія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AE', 'Обʼєднані Арабські Емірати');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('OM', 'Оман');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('AC', 'Острів Вознесіння');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('IM', 'Острів Мен');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('NF', 'Острів Норфолк');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CX', 'Острів Різдва');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SH', 'Острів Святої Єлени');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CK', 'Острови Кука');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PN', 'Острови Піткерн');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TC', 'Острови Теркс і Кайкос');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PK', 'Пакистан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PW', 'Палау');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PS', 'Палестинські території');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PA', 'Панама');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PG', 'Папуа-Нова Ґвінея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PY', 'Параґвай');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PE', 'Перу');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GS', 'Південна Джорджія та Південні Сандвічеві Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KR', 'Південна Корея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SS', 'Південний Судан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ZA', 'Південно-Африканська Республіка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KP', 'Північна Корея');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MK', 'Північна Македонія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MP', 'Північні Маріанські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PL', 'Польща');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PT', 'Портуґалія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('XA', 'Псевдоакценти');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('XB', 'Псевдобіді');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PR', 'Пуерто-Ріко');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('RE', 'Реюньйон');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('RU', 'Росія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('RW', 'Руанда');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('RO', 'Румунія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SV', 'Сальвадор');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('WS', 'Самоа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SM', 'Сан-Маріно');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ST', 'Сан-Томе і Прінсіпі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SA', 'Саудівська Аравія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SC', 'Сейшельські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('BL', 'Сен-Бартельмі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('MF', 'Сен-Мартен');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PM', 'Сен-Пʼєр і Мікелон');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SN', 'Сенегал');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('VC', 'Сент-Вінсент і Ґренадіни');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('KN', 'Сент-Кітс і Невіс');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LC', 'Сент-Люсія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('RS', 'Сербія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('EA', 'Сеута і Мелілья');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SY', 'Сирія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SG', 'Сінгапур');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SX', 'Сінт-Мартен');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SK', 'Словаччина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SI', 'Словенія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SB', 'Соломонові Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SO', 'Сомалі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('US', 'Сполучені Штати');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SD', 'Судан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SR', 'Сурінам');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SL', 'Сьєрра-Леоне');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TJ', 'Таджикистан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TH', 'Таїланд');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TW', 'Тайвань');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TZ', 'Танзанія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TL', 'Тімор-Лешті');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TG', 'Того');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TK', 'Токелау');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TO', 'Тонґа');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TT', 'Трінідад і Тобаґо');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TA', 'Трістан-да-Кунья');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TV', 'Тувалу');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TN', 'Туніс');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TR', 'Туреччина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TM', 'Туркменістан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('UG', 'Уганда');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('HU', 'Угорщина');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('UZ', 'Узбекистан');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('UA', 'Україна');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('WF', 'Уолліс і Футуна');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('UY', 'Уруґвай');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FO', 'Фарерські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FJ', 'Фіджі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PH', 'Філіппіни');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FI', 'Фінляндія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FK', 'Фолклендські Острови');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('FR', 'Франція');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('GF', 'Французька Ґвіана');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('PF', 'Французька Полінезія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TF', 'Французькі Південні Території');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('HR', 'Хорватія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CF', 'Центральноафриканська Республіка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('TD', 'Чад');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CZ', 'Чехія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CL', 'Чілі');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('ME', 'Чорногорія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('CH', 'Швейцарія');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SE', 'Швеція');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('SJ', 'Шпіцберген та Ян-Маєн');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('LK', 'Шрі-Ланка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('JM', 'Ямайка');
INSERT INTO [dbo].[Country] ([CountryCode], [Country]) VALUES ('JP', 'Японія');
